### ISSUE TITLE
Fix Invalid PEM formatted message error in Groth16 Contract

### ISSUE THREAD

**Issue by PrakharSingh0908** [zkemail/zk-regex-registry#30]
![photo_2024-10-12_21-32-46](https://github.com/user-attachments/assets/a48f7182-3070-4eaa-a26f-6d4de8c398d4)

**Comment by Divide-By-0** [comment]
It seems somehow this happens because the deployment script fetches a bad key from the dkim archive, even though simulating it locally seems to work. We need access to the modal and to add more logs to be able to debug this.

**Comment by Divide-By-0** [comment]
To clarify this issue has not been resolved, it's just been rephrased in the new issue.
