### ISSUE TITLE
Not setting DKIM public key

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-regex-registry#36]
We [don't currently update](https://sepolia.etherscan.io/address/0xCD0E07250d70f07BbA71419969E3Ab9840D00A0a) the DKIM on chain registry with the new public keys, but that should happen on proof submission to the chain.

**Comment by javiersuweijie** [comment]
Fixed in: https://github.com/zkemail/zk-regex-registry/pull/38

The issue was the deployer was sending the requests to OP sepolia instead of ETH sepolia
