### ISSUE TITLE
Only recompile circuit when parameters change

### ISSUE THREAD

**Issue by zkemailverify** [zkemail/zk-regex-registry#37]
Don't recompile when only metadata changes that does not affect the circuit

**Comment by javiersuweijie** [comment]
Fixed in: https://github.com/zkemail/zk-regex-registry/pull/38

NOTE: does not yet work for old patterns since the parameters changed and a recompilation will still occur with the new circuit templates

**Comment by Divide-By-0** [comment]
> Fixed in: #38
> 
> NOTE: does not yet work for old patterns since the parameters changed and a recompilation will still occur with the new circuit templates

Will it work for old patterns after a single recompilation?
