### ISSUE TITLE
Add a test email to the compilation

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-regex-registry#8]
This will substantially improve compilation and debugging since people can upload a sample .eml to debug their regexes etc.

This will also allow us to automatically compute the 'Max Email Body Length' after the sha precompute selector.

**Comment by Divide-By-0** [comment]
Also only allow publishing with a green check once a test email has passed

**Comment by javiersuweijie** [comment]
Also able to pick the right DKIM selector from the header.

**Comment by javiersuweijie** [comment]
Added here: https://github.com/zkemail/zk-regex-registry/pull/59

Currently it does not block publishing but that will be added once this feature has been well tested
